domino/__init__.py
domino/domino.py
domino/routes.py
examples/create_project_with_collaborators.py
examples/export_runs.py
examples/publish_api_endpoint.py
examples/start_run_and_check_status.py
examples/unpublish_api_endpoints.py
examples/upload_file.py
setup.py

Add project management endpoints

---

domino/domino.py
domino/routes.py

not really sure what should be returned after the fork. i did a status code but could be a link to the new project, a success message, the project id?

added project forking functionality

---

domino/domino.py
domino/routes.py

I made a thing! 
Verified it worked here - https://app.dominodatalab.com/u/Mac/quick-start/view/domino-app-publishing.ipynb?commitId=24eee1f8c028338dc9d764c220235338d8602aa2
Turning off an app still tbd

Adding App publishing function

---

README.md
domino/domino.py
domino/routes.py

Demo'ed here - https://app.dominodatalab.com/u/Mac/quick-start/view/domino-app-unpublishing.ipynb?commitId=bfa36666d95d4980b9e4f053ed83cee35c9050b4

App republishing and run stopping

---

domino/domino.py
domino/routes.py
examples/models_and_environments.py
setup.py

See issue #36 for details as well

Add model manager (2.5+) APIs

---

README.md

* Added links to download appropriate version
* Added installation instruction for older version (0.3.5)

updated readme.md with links for different python-domino version

---

README.md
domino/constants.py

Lowering `MINIMUM_SUPPORTED_DOMINO_VERSION` to `4.1.0`

[DOM-20757] Update Version Check

---

README.md
domino/domino.py
domino/routes.py
examples/create_project_with_collaborators.py

This P.R fixes the Project Create method.
https://dominodatalab.atlassian.net/browse/DOM-21812

[DOM-21812] Fix project create method

---

domino/domino.py
domino/routes.py
setup.py

This P.R fixes stop run in python domino

[DOM-20306] Fix Stop Run Python Domino

---

CHANGELOG.md
README.md

* Fixed Readme
* Added Change log

[DOM-20306] Fix Readme

---

domino/constants.py

In domino 4.6 we want to support launching Dask jobs from this package
Add support for launching Dask jobs
https://dominodatalab.atlassian.net/browse/DOM-29496

Support dask job launching for 4.6 and higher

---

README.md

Fixing Python egg name in the airflow operator installation guidelines.
Fixing some discrepancies found during testing.

Some readme modifications

---

domino/constants.py
domino/domino.py
domino/exceptions.py
domino/helpers.py

This PR adds the ability to start jobs with compute clusters that can autoscale.
https://dominodatalab.atlassian.net/browse/DOM-31483

Add, validate, and document autoscaling configuration for jobs_start

---

CHANGELOG.md
domino/domino.py

change version number logging level to debug to avoid annoying message. https://dominodatalab.atlassian.net/browse/DOM-34847

[DOM-34847]change version logging to debg

---

README.adoc

[DOCS-1533](https://dominodatalab.atlassian.net/browse/DOCS-1533)
resolve some formatting and wording issues
remove unnecessary starts and underscores in readme

[DOCS-1533] - updated formatting

---

CHANGELOG.md
README.adoc
README.md

[RM-2362](https://dominodatalab.atlassian.net/browse/RM-2362)
Domino 5.7.0 
Create new python-domino
Updated python Version to 1.2.4 and create new release. - https://pypi.org/project/dominodatalab/
Create a new clean python environment, and run `pip install dominodatalab`
- latest version should be installed.

[RM-2362] - Releasing python version 1.2.4

---

README.adoc

[DOM-XYZ](https://dominodatalab.atlassian.net/browse)
_placeholder_
_placeholder_

Fix docs link

---

README.md

[DOM-XYZ](https://dominodatalab.atlassian.net/browse)
_placeholder_
_placeholder_

Fix doc links in readme

---

README.adoc
README.md

[DOM-XYZ](https://dominodatalab.atlassian.net/browse)
_placeholder_
_placeholder_

Fix docs links release-1.2.4

---

CHANGELOG.md

Updating Changelog file

---

CHANGELOG.md
README.adoc
README.md
domino/datasets.py
domino/domino.py
tests/test_datasets.py

https://dominodatalab.atlassian.net/browse/DOM-53774
https://dominodatalab.atlassian.net/browse/DOM-53775
https://dominodatalab.atlassian.net/browse/DOM-53779
https://dominodatalab.atlassian.net/browse/DOM-53780
Take care of them
_placeholder_

datasetRw: upload bug fixes

---

domino/domino.py
tests/test_datasets.py
tests/test_jobs.py
tests/test_spark_operator.py

[RM-3528](https://dominodatalab.atlassian.net/browse/RM-3528)
Some tests were out of date with changes with the API responses
Validate that functionalities remain
Update jobs tests to align with API changes

updated testing

---

README.adoc
README.md

[RM-4608](https://dominodatalab.atlassian.net/browse/RM-4608)
* #214
Release new version 1.4.5

[RM-4608] Creating release version 1.4.5
