- README.md
- domino/domino.py
- domino/routes.py
The purpose of this PR is to do the following:
- Beautify the readme file
- Add routes and methods for getting stdout of a run.  Need this functionality in order to integrate Domino with [Airflow](https://airflow.incubator.apache.org/)
- Added methods that make blocking calls and wait for the task to complete, and emit standard out.
cc: @johnjoo1 @ChuckRIHead
> Beautify Readme and add routes for blocking calls and stdout

- README.md
- domino/domino.py
Updates `app_publish` to accept an optional `hardwareTierId` parameter which is introduced to the api in https://github.com/cerebrotech/domino/pull/14351.
See https://dominodatalab.atlassian.net/browse/DOM-12518 for more details.
> DOM-12518: update python client to account for new hardware tier argument for app publishing

- domino/domino.py
- domino/routes.py
The path /u/<user_name>/<project_name>/endpoints returns a 404 code now in newer versions of Domino. It seems we have internally updated the path to be /u/<user_name>/<project_name>/endpoints/modelManager, so publish_ui() function was updated to reflect the change. Without this fix, anything that relies on publish_ui() breaks. This particular code breaks:
https://github.com/dominodatalab/python-domino/blob/master/domino/domino.py#L380-L390
> Fixed publish_ui() to use updated URL in Domino

- domino/domino.py
- domino/routes.py
These methods weren't working because of missing that endpoints
*app_publish* : The route `/nb/startsession` called by this method was removed [here](https://github.com/cerebrotech/domino/pull/18039)
*app_unpublish*: The route `/run/stop` called by this method was removed.
In this P.R I have replaced the above routes with these
*app_publish*: `POST https://{Host-Url}/v4/modelProducts/{app_id}/start`
*app_unpublish*: `POST https://{Host-Url}/v4/modelProducts/{app_id}/stop`
Note:
1. For retrieving the `app_id` used in above routes, I am using following endpoint
`GET https://{Host-Url}/v4/modelProducts?projectId={project_id}`
2. If app doesn't exists. The method will first try to create one. For this I am using following endpoint
`POST https://{Host-Url}/v4/modelProducts`
Verified this on …
> [DOM-20307][DOM-20308] Fix publish/un-publish App

- README.md
- domino/domino.py
Currently in `runs_start_blocking` method, if Http request fails because of transient http errors, the method fails. 
This P.R adds a `retry` param, which will retry the request incase of transient http errors
https://dominodatalab.atlassian.net/browse/DOM-21559
Case Method fails after Max retries
Case Method succeeds after 2 failed request.
> [DOM-21559] Add `retry` param in `runs_start_blocking`

- README.md
- domino/airflow/__init__.py
- domino/airflow/_operator.py
- domino/domino.py
- examples/example_airflow_dag.py
- setup.py
Is there any interest in taking work that I've done to make a `DominoOperator` for airflow and bundling it with this project as an optional extra package? 
As a bonus side effect it could help greatly clean up the documentation in this section: https://docs.dominodatalab.com/en/4.1/reference/runs/advanced/Using_Apache_Airflow_with_Domino.html
The `PythonOperator` is recommended, but as an end user there are some pitfalls...
We use this internally for scheduling runs and it has some extra features to work around kinks of the API, mainly the fact that setup for runs isn't logged by default and functionality to help mitigate the race condition in 3.6 when scheduling multiple runs in parallel.
I would consider adding it to Airflow's operator contrib repository proper but I don't think there …
> Airflow DominoOperator

- .gitignore
- domino/airflow/_operator.py
- domino/domino.py
- tests/test_operator.py
Fixes #63 
Also adds some code to remove `bs4` related warnings by defaulting to the built in parser.
> DominoOperator logging fix

- .gitignore
- domino/airflow/_operator.py
- domino/domino.py
- tests/test_operator.py
fixes #67, updates logging in accordance with changes from #69.
The way that the `runs_start_blocking` method logs through the exception msg made it hard to catch and handle cleanly, instead I moved around the log processor from the Domino operator and re-factored it to use the new `.log` property which plays nice with airflow. 
Open to suggestions if you guys don't like this behavior, the cost of not fixing it is ugly formatting for logs on airflow job failure, since a pretty printed string is what is passed through the exception (which I then have to de-pretty print), I think ideally we'd get a raw log.
> add hardwaretier validation; adjust run logging

- CHANGELOG.md
- README.md
- domino/constants.py
- domino/domino.py
- domino/exceptions.py
- domino/helpers.py
- domino/http_request_manager.py
- domino/routes.py
- setup.py
This P.R adds following v4 API endpoints
```
def job_start(self, command, commit_id=None, hardware_tier_name=None,
environment_id=None, on_demand_spark_cluster_properties=None):
def job_stop(self, job_id, commit_results=True):
def job_status(self, job_id):
def job_start_blocking(self, poll_freq=5, max_poll_time=6000, **kwargs):
```
In this P.R i have added a new dependency `[polling2](https://pypi.org/project/polling2/)`, for blocking start job method.
#70 
https://dominodatalab.atlassian.net/browse/DOM-23072
> [DOM-23072] Add on demand spark cluster support to domino python package via v4 API to start job

- README.md
- domino/airflow/__init__.py
- domino/airflow/_operator.py
- domino/domino.py
- pytest.ini
- tests/scripts/test_spark.py
- tests/scripts/test_spark_fail.sh
- tests/test_operator.py
- tests/test_spark_operator.py
Add new `DominoSparkOperator` that supports the v4 job start function signature along with associated unit tests.
> DominoSparkOperator

- CHANGELOG.md
- domino/domino.py
- domino/routes.py
The domino server responds with 500 when we attempt to stop an App that is already stopped.
Note: this change does not completely eliminate the possibility of a race condition when another client stops an App between the time we check its status and issue a stop request.
> Check if the App is running before stopping

- domino/constants.py
- domino/domino.py
- domino/helpers.py
This PR adds compute cluster support to the start job endpoint. This looks like it is the only endpoint that can launch cluster related executions, so I only added it there.
There doesn't seem to be a standardized way for doing input validation, yet there is input validation on the start job endpoint, so I added basic input validation for the compute cluster definition. I did not do validation on whether the HWTs or env ids exist or not, because domino will reject with informative messaging if that is the case.
https://dominodatalab.atlassian.net/browse/DOM-27821
> Add compute cluster properties to job launching

- CHANGELOG.md
- README.md
Version from `_version.py` already bumped in [a previous PR](https://github.com/dominodatalab/python-domino/pull/85).
> Release `python-domino` 1.0.4

- setup.py
- tests/test_basic_auth.py
Create a set of simple unit tests to confirm authentication works.
These can serve as a way to guarantee that any future development
or refactoring won't introduce regressions.
No other code was changed in ths PR. This is only new test code.
Note that two of the tests are strict unit tests and rely on mocking
to confirm proper behavior. The remaining tests require an actual
live deployment, and some special tooling. If these requirements
can't be met, then the tests will either be skipped or will xfail.
Sample test run:
```
% DOMINO_HOST_KEY_NAME=<redacted> DOMINO_API_KEY_KEY_NAME=<redacted> pytest -sv tests/test_basic_auth.py
====================================== test session starts ======================================
cachedir: .pytest_cache
rootdir: /path/to/python-domino, …
```
> Add authentication unit tests

- setup.py
Version string in test_requires doesn't handle ~= operator.
This PR addresses issue #95.
Tested this works from a remote repo:
```
% pip install git+https://github.com/<gh_user>/python-domino.git@fix_setup_py_syntax#egg=python-domino
Looking in indexes: https://pypi.org/simple, https://ddl-pypi-reader:****@domino.jfrog.io/domino/api/pypi/pypi-local/simple
Obtaining python-domino from git+https://github.com/<gh_user>/python-domino.git#egg=python-domino
Cloning https://github.com/<gh_user>/python-domino.git to ./fix_domino_setup/src/python-domino
Running command git clone -q https://github.com/<gh_user>/python-domino.git /private/tmp/fix_domino_setup/src/python-domino
Collecting requests>=2.4.2
Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting bs4==0.*,>=0.0.1
Using …
```
> Fix syntax error in setup.py test_requires value

- domino/helpers.py
- tests/test_basic_auth.py
This function was written as a helper in one test file, but it could
be generally imported and used by others if we move it to helpers.py.
Testing:
Unit tests that know about this function still pass after the move.
```
tests/test_basic_auth.py::test_object_creation_with_api_key PASSED
tests/test_basic_auth.py::test_object_creation_with_token_file PASSED
tests/test_basic_auth.py::test_auth_against_real_deployment_with_api_key PASSED
tests/test_basic_auth.py::test_auth_against_real_deployment_with_token_file PASSED
```
> Move domino_is_reachable to helpers.py

- CHANGELOG.md
- domino/domino.py
- tests/conftest.py
- tests/test_basic_auth.py
- tests/test_jobs.py
The actual code change here is very small -- the bulk of the changes
is new/edited test code.
Before this patch, starting a blocking job would ignore any HTTP
errors when checking for job status to complete, until polling finally
timed out. This change allows a user to specify which exceptions to
ignore by passing a tuple (which is the data type required by the
polling2 library) of ignored exceptions. Providing an empty tuple
means that no exceptions are ignored.
The original default behavior was not changed.
On the test side:
- a new unit test file was added: test_jobs.py
- fixtures were moved to a new conftest.py file to be more
accessible across different tests
New and previous unit tests are passing
```
cachedir: .pytest_cache
rootdir: /path/to/dominodatalab/python-domino, configfile: …
```
> Permit customizing ignored exceptions when polling job status

- CHANGELOG.md
- domino/domino.py
- domino/exceptions.py
- domino/http_request_manager.py
Added better token expiration error handling for `job_start` and `runs_start` methods (the latter is not really necessary right now as it uses v1 API).
> Better error if auth token needs refresh when running jobs

- CHANGELOG.md
- README.md
- domino/authentication.py
- domino/domino.py
- tests/test_basic_auth.py
When instantiating `Domino` object, the authentication preference should always be given to the authentication token. If it's not passed, the path to domino token file takes precedence, otherwise the API key is used. If none of these three parameters are passed, then preference will be given to the domino token file from the corresponding environment variable, then to the API key from the corresponding environment variable.
> Fixing precedence of authentication methods

- CHANGELOG.md
- domino/data_sources.py
- tests/test_data_sources.py
- tox.ini
https://dominodatalab.atlassian.net/browse/DOM-38900
Implementation of __getattr__ is not looking for objects in the right module
Use `getattr` on the right module
Tested in a deployment (by upload tar dist and installing manually)
> Fix issues with missing import from domino-data

- CHANGELOG.md
- domino/domino.py
- tests/test_projects.py
[DOM-39831](https://dominodatalab.atlassian.net/browse)
When a file that is being uploaded does not have a forward slash at the beginning it throws an error
Added a checker to make sure the file still gets uploaded either way.
- https://github.com/dominodatalab/python-domino/issues/33
> [DOM-39831] - added forward slash check for file upload

- domino/authentication.py
- domino/http_request_manager.py
[DOM-40084](https://dominodatalab.atlassian.net/browse/DOM-40084)
python-domino api tracker was only tracking calls that required auth, therefore leaving some endpoints not covered
move header changes to request manager
> [DOM-40084] - fixed domino api tracker bug

- README.md
- domino/authentication.py
- tests/test_basic_auth.py
[DOM-41687](https://dominodatalab.atlassian.net/browse/DOM-41687)
The Domino API Proxy is now a reverse proxy
Intercept requests, replace API host/port with proxy host/port
Unit tests
> DOM-41687 Use reverse proxy for authentication.

- CHANGELOG.md
- setup.py
[DOM-42181](https://dominodatalab.atlassian.net/browse/DOM-42181)
Python domino fails on installation of python < 3.8
Limits minimum version of python required to install newer version of python-domino
Installation testing
> [DOM-42181] - set minimum python versions requirement

- CHANGELOG.md
- domino/domino.py
- examples/models_and_environments.py
- setup.py
- tests/conftest.py
- tests/test_operator.py
- tests/test_spark_operator.py
[DOM-43066](https://dominodatalab.atlassian.net/browse/DOM-43066)
- https://github.com/dominodatalab/python-domino/issues/153
- DominoSparkOperator not fully usable with python 3.7 due to min requirements
- fix bugs in test
- set python minimum requirements to 3.7
- Updated unit test
- setup new python environment with 3.7 `pipenv install --python 3.7` and install and test python-domino
> [DOM-43066] - DominoSparkOperator update

- CHANGELOG.md
- README.adoc
- domino/domino.py
- domino/routes.py
- examples/upload_and_run_file_and_download_results.py
- tests/test_projects.py
[DOM-51572](https://dominodatalab.atlassian.net/browse)
blobs_get needs to be deprecated in favor of a more secure endpoint. This will not need to go in 5.9 - so the PR will stay open for some time.
deprecate it and add new endpoint!
> Deprecate blobs_get and open blobs_get_v2

- README.md
- domino/datasets.py
- domino/domino.py
- domino/routes.py
- requirements.txt
- tests/test_datasets.py
[DOM-52840](https://dominodatalab.atlassian.net/browse)
Needed a new endpoint to handle dataset upload
Add endpoint as well as full client implementation + tests for single file, multi-part, multi-thread uploads
> datasetRw: add dataset upload file capabilities to domino-python (multi-part, multi-thread)

- README.adoc
- README.md
- domino/domino.py
- tests/test_datasets.py
Cleanup for naming and docs purposes
> datasetRw Upload - naming and readMe

- CHANGELOG.md
- domino/domino.py
- tests/test_domino.py
[DOM-53368](https://dominodatalab.atlassian.net/browse/DOM-53368)
domino version checker is failing to correctly assert num-string with base less than 10
use package version
> [DOM-53368] - fix version checker

- CHANGELOG.md
- README.adoc
- README.md
- domino/datasets.py
- domino/domino.py
- setup.py
- tests/test_datasets.py
https://dominodatalab.atlassian.net/browse/DOM-53784 + revert of interactive part + more thorough docstrings
Retry in setup.py
Add it
> need retry package in setup.py + no interactivity

- setup.py
[DOM-53784](https://dominodatalab.atlassian.net/browse/DOM-53784)
Need the retry dependency in install_requires, not merely the dev specialization in extra_requires.
Need the retry dependency in install_requires, not merely the dev specialization in extra_requires.
Pip installed from this branch instead of master and observed that I could upload files to datasets.
> [DOM-53784] Adjust retry dependency declaration

- domino/flyte/task.py
https://dominodatalab.atlassian.net/browse/DOM-52824
Flyte input downloader init container and output uploader sidecar container need the interfaces for the input/output provided as args to their container commands in base64 string encoded format.
After instantiating the DominoTask, serialize the tasks input/output interfaces to base64 string and provide those as job config so they can be sent along to the job api by the flyte agent.
Tested the serialized args produced from the python code with an arbitrary domino job that uses the init and sidecar containers, and placed data matching the interface at the expected input location in s3. Init sidecar downloaded the data, the code used the data and saved to the local output dir, then the sidecar successfully uploaded the output to s3.
> [DOM-52828] Add interface vals to the domino task

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.adoc
- README.md
- domino/http_request_manager.py
- setup.py
- tests/test_basic_auth.py
- tests/test_domino.py
[DOM-54635](https://dominodatalab.atlassian.net/browse/DOM-54635)
Some long-running jobs are failing with ConnectionError due to connections being dropped.
We updated the request session with configurable retries to support connection timeouts, preventing long-running jobs from failing due to connection drops or long timeouts.
> [DOM-54635] - updated requests session with retry

- CHANGELOG.md
- setup.py
https://dominodatalab.atlassian.net/browse/DOM-57187
Solve the dependency conflicts in DSEs
bump up the version of type-extensions.
> DOM-57187 - bump up typing-extensions version to solve conflicts

- CHANGELOG.md
- domino/datasets.py
- tests/assets/back\slash.txt
- tests/test_datasets.py
[DOM-59086](https://dominodatalab.atlassian.net/browse/DOM-59086)
On Windows machines, filepaths contain `\` separators whereas the upload endpoint expects Unix-style `/` separators. This results in files not being uploaded properly on Windows. This is fixed for upload files (PR: https://github.com/dominodatalab/python-domino/pull/203). But the issue remains for uploading folders.
Replace Windows-style separators with Unix-style ones when uploading content from a folder.
Created unit test and manual test for uploading a non-empty folder on a Windows machine to a Dataset.
> [DOM-59086] Fix uploading Folder to Dataset on Windows

- requirements.txt
- setup.py
https://dominodatalab.atlassian.net/browse/QE-17483
urllib3 is too tightly constrained
loosens the urllib3 version for compliance with openapi generated clients
- Tested locally
- Tested using CI (see ticket details)
> QE-17483 loosen urllib3 version

- domino/domino.py
- domino/routes.py
[PS-13958](https://onedominodatalab.atlassian.net/browse/PS-13958)
Extends the query functionality of jobs_list() to include as many of the options available in Domino's REST API as possible.
Added additional arguments and set their default values to match those in the REST API.
Tested by listing previous jobs in a project. As the function explicitly sends the default API values, it uses all of the query parameters by default.
> [PS-13958] - Extend options for listing jobs

- domino/aisystems/tracing/tracing.py
- tests/integration/aisystems/test_aisystems_tracing.py
The search_traces API defaults to using a filter start time of 1 hour ago. This was intended to limit the amount of data pulled into memory when there are many traces.
However, this API is now paginated and we don’t let the user get all traces at once. This default is not necessary. It is also confusing, because users may try to retrieve traces that were created over an hour ago by not specifying a start time. this was the case in a recent bug bash.
This PR also fixes a bug where the run_id wasn't being used correctly as a filter. traces from all runs in the experiment would appear in the response in stead of just the specified run.
https://dominodatalab.atlassian.net/browse/DOM-70889
https://dominodatalab.atlassian.net/browse/DOM-70905
_placeholder_
_placeholder_
Briefly describe how the …
> DOM-70889 DOM-70905  remove start time default and fix bug with filtering by run_id

- domino/aisystems/logging/dominorun.py
- tests/integration/aisystems/test_domino_run.py
https://dominodatalab.atlassian.net/browse/DOM-71068
Confuses user as the metric names are confusing since they don’t include the agg methodology
- Aggregation metric names now use <agg_type>_<metric_name>.
- recompute all aggregation metrics in subsequent runs just in case new traces have arrived
> DOM-71068 add differentiated agg labels in dominorun

- setup.py
https://dominodatalab.atlassian.net/browse/DOM-71264
we have had lots of trouble with mlflow pushing breaking chagnes into their sdk, we must pin the version that we install in the python-domino repo. for some reason it was not pinned
_placeholder_
_placeholder_
> DOM-71264 Pin mlflow
